name: soko_beauty
description: "Soko Beauty mobile app."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.1.5 <4.0.0"

# main dependencies
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  intl: ^0.19.0
  dartz: ^0.10.1

  # navigation dependencies
  http: ^1.2.0
  marquee: ^2.2.3

  # video dependencies
  video_player: ^2.8.2

  # post dependencies
  equatable: ^2.0.5
  permission_handler: ^11.3.0
  camera: ^0.10.5+9

  # state management
  flutter_bloc: ^8.1.3
  provider: ^6.1.1

  # auth dependencies
  email_validator: ^2.1.17

  #firebase dependencies
  cloud_firestore: ^4.15.8
  firebase_auth: ^4.17.8

  # file management
  image_picker: ^1.0.7
  firebase_storage: ^11.6.9
  file_picker: ^8.0.0+1
  open_file: ^3.3.2

  # ui dependencies
  smooth_page_indicator: ^1.1.0
  carousel_slider: ^4.2.1
  flutter_svg: 2.0.10+1
  table_calendar: ^3.1.1
  visibility_detector: ^0.4.0+2
  cloudinary_flutter: ^1.3.0
  firebase_messaging: ^14.9.4
  # flutter_local_notifications: ^17.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  bloc_test: ^9.1.4
  mocktail:

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  windows: "launcher_icon"
  image_path: "assets/launcher_icon.png"
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/user_avatar.png
    - assets/1015-300x201.jpg
    - assets/icons/ios.png
    - assets/icons/ios-white.png
    - assets/icons/facebook.png
    - assets/icons/google.png
    - assets/gif/shop.gif
    - assets/gif/beauty_video.gif
    - assets/gif/make_up.gif
    - assets/gif/nothing.gif
